export const TO_INFO_GROUP_FOCUS_SITE = "FOCUS_SITE";
export const TO_INFO_GROUP_COLLECTIONS = "COLLECTIONS";
export const TO_PUBLISH_TOPIC = "PUBLISH_TOPIC";
export const TO_PUBLISH_COMMENT = "PUBLISH_COMMENT";